---
version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "%(asctime)s %(levelname)s %(module)s %(message)s"
  fancy:
    format: "%(asctime)s|%(levelname)s|%(module)s.%(funcName)s:%(lineno)-2s|%(message)s"
  debug:
    format: "%(asctime)s|%(levelname)s|%(pathname)s:%(funcName)s:%(lineno)-2s|%(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  screen:
    class: logging.StreamHandler
    level: DEBUG 
    formatter: fancy
    stream: ext://sys.stdout
  
  logfile:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: fancy
    filename: "/tmp/deployVpc.log"
    maxBytes: 1000000
    backupCount: 10
    encoding: utf8
  
  logfile_debug:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: debug
    filename: "/tmp/deployVpc.log"
    maxBytes: 1000000
    backupCount: 10
    encoding: utf8

loggers:
  boto:
    level: DEBUG
    handlers: [logfile_debug]
    propagate: no
  boto3:
    level: DEBUG
    handlers: [logfile_debug]
    propagate: no
  botocore:
    level: DEBUG
    handlers: [logfile_debug]
    propagate: no
  deployVpc:
    level: DEBUG
    handlers: [logfile_debug, screen]
    propagate: no
  __main__:
    level: DEBUG
    handlers: [logfile_debug, screen]
    propagate: no

root:
  level: NOTSET
  handlers: [console, logfile_debug]
